export interface IconCategory {
  id: string
  label: string
  icon: string
  icons: string[]
}

export const iconCategories: IconCategory[] = [
  {
    id: 'transport',
    label: 'Транспорт',
    icon: 'mdi:car',
    icons: [
      'mdi:car',
      'mdi:car-sports',
      'mdi:car-convertible',
      'mdi:car-pickup',
      'mdi:car-estate',
      'mdi:car-key',
      'mdi:car-wash',
      'mdi:train',
      'mdi:train-variant',
      'mdi:tram',
      'mdi:subway',
      'mdi:airplane',
      'mdi:airplane-takeoff',
      'mdi:airplane-landing',
      'mdi:bus',
      'mdi:bus-clock',
      'mdi:taxi',
      'mdi:ferry',
      'mdi:sail-boat',
      'mdi:ship-wheel',
      'mdi:bike',
      'mdi:bicycle',
      'mdi:motorbike',
      'mdi:walk',
      'mdi:run',
      'mdi:truck',
      'mdi:van-utility',
      'mdi:helicopter',
      'mdi:rocket-launch-outline',
      'mdi:gas-station',
      'mdi:parking',
      'mdi:road-variant',
      'mdi:map-marker-path',
      'mdi:steering',
    ],
  },
  {
    id: 'food',
    label: 'Еда и напитки',
    icon: 'mdi:food-fork-drink',
    icons: [
      'mdi:food-fork-drink',
      'mdi:silverware-fork-knife',
      'mdi:chef-hat',
      'mdi:coffee-outline',
      'mdi:tea-outline',
      'mdi:cup-outline',
      'mdi:beer-outline',
      'mdi:wine',
      'mdi:bottle-wine',
      'mdi:glass-cocktail',
      'mdi:pizza',
      'mdi:hamburger',
      'mdi:hot-dog',
      'mdi:noodles',
      'mdi:sushi',
      'mdi:food-croissant',
      'mdi:baguette',
      'mdi:bread-slice-outline',
      'mdi:cake-variant-outline',
      'mdi:cupcake',
      'mdi:ice-cream',
      'mdi:candy-outline',
      'mdi:food-apple-outline',
      'mdi:food-drumstick-outline',
      'mdi:fish',
      'mdi:shrimp',
      'mdi:egg-fried',
      'mdi:corn',
      'mdi:cheese',
      'mdi:fruit-grapes',
      'mdi:fruit-watermelon',
      'mdi:bowl-mix-outline',
      'mdi:pot-outline',
      'mdi:grill-outline',
    ],
  },
  {
    id: 'places',
    label: 'Места',
    icon: 'mdi:map-marker-outline',
    icons: [
      'mdi:map-marker-outline',
      'mdi:map-marker',
      'mdi:map-marker-star-outline',
      'mdi:map-marker-radius-outline',
      'mdi:map-search-outline',
      'mdi:map-outline',
      'mdi:city',
      'mdi:city-variant-outline',
      'mdi:home-city-outline',
      'mdi:castle',
      'mdi:bridge',
      'mdi:lighthouse-on',
      'mdi:bank-outline',
      'mdi:church',
      'mdi:mosque',
      'mdi:synagogue',
      'mdi:temple-hindu-outline',
      'mdi:fountain',
      'mdi:monument',
      'mdi:tower-fire',
      'mdi:stadium-variant',
      'mdi:airport',
      'mdi:bus-stop',
      'mdi:train-station',
      'mdi:hospital-building',
      'mdi:school-outline',
      'mdi:library-outline',
      'mdi:theater',
      'mdi:museum',
      'mdi:art-outline',
      'mdi:office-building-outline',
      'mdi:store-outline',
      'mdi:warehouse',
      'mdi:home-variant-outline',
    ],
  },
  {
    id: 'accommodation',
    label: 'Жильё',
    icon: 'mdi:bed-outline',
    icons: [
      'mdi:bed-outline',
      'mdi:bed-queen-outline',
      'mdi:bed-king-outline',
      'mdi:bunk-bed-outline',
      'mdi:sofa-outline',
      'mdi:home-outline',
      'mdi:home-variant-outline',
      'mdi:home-account',
      'mdi:home-heart',
      'mdi:home-city-outline',
      'mdi:tent',
      'mdi:caravan',
      'mdi:cabin-a-frame',
      'mdi:greenhouse',
      'mdi:star-outline',
      'mdi:star-half-full',
      'mdi:key-variant',
      'mdi:door-open',
    ],
  },
  {
    id: 'activity',
    label: 'Активности',
    icon: 'mdi:hiking',
    icons: [
      'mdi:hiking',
      'mdi:run',
      'mdi:walk',
      'mdi:yoga',
      'mdi:swim',
      'mdi:beach',
      'mdi:ski',
      'mdi:ski-water',
      'mdi:snowboard',
      'mdi:skate',
      'mdi:kayaking',
      'mdi:diving-scuba',
      'mdi:paragliding',
      'mdi:bike',
      'mdi:horse-variant',
      'mdi:golf',
      'mdi:tennis',
      'mdi:soccer',
      'mdi:basketball',
      'mdi:volleyball',
      'mdi:bowling',
      'mdi:handball',
      'mdi:campfire',
      'mdi:summit',
      'mdi:pine-tree',
      'mdi:forest',
      'mdi:binoculars',
    ],
  },
  {
    id: 'nature',
    label: 'Природа',
    icon: 'mdi:tree-outline',
    icons: [
      'mdi:tree-outline',
      'mdi:forest',
      'mdi:pine-tree',
      'mdi:palm-tree',
      'mdi:cactus',
      'mdi:flower-outline',
      'mdi:flower-tulip-outline',
      'mdi:leaf',
      'mdi:leaf-maple',
      'mdi:mushroom-outline',
      'mdi:grass',
      'mdi:sprout-outline',
      'mdi:seed-outline',
      'mdi:water',
      'mdi:waves',
      'mdi:beach',
      'mdi:island',
      'mdi:terrain',
      'mdi:volcano-outline',
      'mdi:weather-sunny',
      'mdi:weather-night',
      'mdi:weather-cloudy',
      'mdi:weather-rainy',
      'mdi:weather-snowy',
      'mdi:weather-lightning',
      'mdi:weather-windy',
      'mdi:weather-fog',
      'mdi:sun-snowflake',
      'mdi:bird',
      'mdi:butterfly-outline',
      'mdi:fish',
      'mdi:paw-outline',
      'mdi:rabbit',
      'mdi:cat',
      'mdi:dog',
      'mdi:elephant',
      'mdi:penguin',
      'mdi:turtle',
    ],
  },
  {
    id: 'shopping',
    label: 'Шопинг',
    icon: 'mdi:shopping-outline',
    icons: [
      'mdi:shopping-outline',
      'mdi:cart-outline',
      'mdi:cart-heart',
      'mdi:bag-personal-outline',
      'mdi:bag-suitcase-outline',
      'mdi:briefcase-outline',
      'mdi:gift-outline',
      'mdi:gift-open-outline',
      'mdi:tag-outline',
      'mdi:tag-multiple-outline',
      'mdi:sale',
      'mdi:percent',
      'mdi:store-outline',
      'mdi:storefront-outline',
      'mdi:hanger',
      'mdi:tshirt-crew-outline',
      'mdi:shoe-formal',
      'mdi:hat-fedora',
      'mdi:glasses',
      'mdi:watch',
      'mdi:ring',
      'mdi:diamond-stone',
      'mdi:necklace',
      'mdi:purse-outline',
      'mdi:wallet-outline',
    ],
  },
  {
    id: 'entertainment',
    label: 'Развлечения',
    icon: 'mdi:party-popper',
    icons: [
      'mdi:party-popper',
      'mdi:balloon',
      'mdi:firework',
      'mdi:music-note-outline',
      'mdi:music',
      'mdi:headphones',
      'mdi:microphone-outline',
      'mdi:guitar-electric',
      'mdi:piano',
      'mdi:saxophone',
      'mdi:violin',
      'mdi:theater',
      'mdi:television-play',
      'mdi:ticket-outline',
      'mdi:ticket-confirmation-outline',
      'mdi:gamepad-variant-outline',
      'mdi:dice-multiple-outline',
      'mdi:puzzle-outline',
      'mdi:cards-playing-outline',
      'mdi:chess-king',
      'mdi:ferris-wheel',
      'mdi:camera-outline',
      'mdi:image-outline',
    ],
  },
  {
    id: 'finance',
    label: 'Финансы',
    icon: 'mdi:cash-multiple',
    icons: [
      'mdi:cash-multiple',
      'mdi:cash',
      'mdi:cash-100',
      'mdi:credit-card-outline',
      'mdi:bank-outline',
      'mdi:wallet-outline',
      'mdi:piggy-bank-outline',
      'mdi:safe-square-outline',
      'mdi:currency-usd',
      'mdi:currency-eur',
      'mdi:currency-rub',
      'mdi:currency-gbp',
      'mdi:currency-jpy',
      'mdi:currency-cny',
      'mdi:currency-btc',
      'mdi:currency-eth',
      'mdi:receipt-outline',
      'mdi:receipt-text-outline',
      'mdi:calculator-variant-outline',
      'mdi:chart-line-variant',
      'mdi:chart-bar-stacked',
      'mdi:chart-pie-outline',
      'mdi:trending-up',
      'mdi:trending-down',
      'mdi:percent',
      'mdi:sale',
      'mdi:tag-outline',
      'mdi:shopping-outline',
      'mdi:food-fork-drink',
      'mdi:car',
      'mdi:home-outline',
      'mdi:airplane',
      'mdi:hospital-building',
      'mdi:school-outline',
    ],
  },
  {
    id: 'documents',
    label: 'Документы',
    icon: 'mdi:file-document-outline',
    icons: [
      'mdi:file-document-outline',
      'mdi:file-document-multiple-outline',
      'mdi:passport',
      'mdi:card-account-details-outline',
      'mdi:ticket-outline',
      'mdi:ticket-confirmation-outline',
      'mdi:clipboard-outline',
      'mdi:clipboard-list-outline',
      'mdi:note-outline',
      'mdi:note-multiple-outline',
      'mdi:bookmark-outline',
      'mdi:bookmark-multiple-outline',
      'mdi:pin-outline',
      'mdi:flag-outline',
      'mdi:flag-variant-outline',
      'mdi:calendar-outline',
      'mdi:calendar-check-outline',
      'mdi:calendar-clock',
      'mdi:calendar-range-outline',
      'mdi:clock-outline',
      'mdi:alarm',
      'mdi:timer-outline',
      'mdi:email-outline',
      'mdi:phone-outline',
      'mdi:map-outline',
      'mdi:qrcode',
      'mdi:barcode-scan',
      'mdi:printer-outline',
      'mdi:folder-outline',
      'mdi:folder-open-outline',
      'mdi:link-variant',
      'mdi:attachment',
    ],
  },
  {
    id: 'checklist',
    label: 'Чеклисты',
    icon: 'mdi:checkbox-marked-outline',
    icons: [
      'mdi:checkbox-marked-outline',
      'mdi:check-circle-outline',
      'mdi:list-status',
      'mdi:format-list-checks',
      'mdi:format-list-bulleted',
      'mdi:format-list-numbered',
      'mdi:bag-checked',
      'mdi:bag-personal-outline',
      'mdi:bag-suitcase-outline',
      'mdi:tshirt-crew-outline',
      'mdi:shoe-formal',
      'mdi:hat-fedora',
      'mdi:glasses',
      'mdi:sunglasses',
      'mdi:toothbrush-paste',
      'mdi:lotion-outline',
      'mdi:pill',
      'mdi:medical-bag',
      'mdi:shield-check-outline',
      'mdi:umbrella-outline',
      'mdi:power-plug-outline',
      'mdi:phone-outline',
      'mdi:camera-outline',
      'mdi:laptop',
      'mdi:headphones',
      'mdi:passport',
      'mdi:cash',
    ],
  },
  {
    id: 'misc',
    label: 'Разное',
    icon: 'mdi:dots-grid',
    icons: [
      'mdi:star-outline',
      'mdi:star',
      'mdi:heart-outline',
      'mdi:lightning-bolt-outline',
      'mdi:shield-outline',
      'mdi:crown-outline',
      'mdi:key-outline',
      'mdi:lock-outline',
      'mdi:eye-outline',
      'mdi:magnify',
      'mdi:information-outline',
      'mdi:alert-outline',
      'mdi:fire',
      'mdi:snowflake',
      'mdi:diamond-outline',
      'mdi:trophy-outline',
      'mdi:medal-outline',
      'mdi:certificate-outline',
      'mdi:rocket-launch-outline',
      'mdi:earth',
      'mdi:globe-model',
      'mdi:compass-outline',
      'mdi:binoculars',
      'mdi:telescope',
      'mdi:account-outline',
      'mdi:account-group-outline',
      'mdi:hand-wave-outline',
      'mdi:emoticon-outline',
      'mdi:chat-outline',
      'mdi:share-variant-outline',
      'mdi:bell-outline',
      'mdi:cog-outline',
      'mdi:dots-horizontal',
    ],
  },
]

export const sharedIconList = iconCategories.flatMap(cat => cat.icons)
