# Этап 1: Сборщик (Builder)
FROM oven/bun:1-slim AS builder

WORKDIR /usr/src/app

COPY package.json ./
RUN bun install
COPY . .
RUN bun run build


# Этап 2: Финальный образ (Production)
FROM oven/bun:1-slim

RUN apt-get update && apt-get install -y --no-install-recommends libvips && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

ENV NODE_ENV=production
ENV PORT=8080

COPY package.json ./
RUN bun install --production --frozen-lockfile

COPY --from=builder /usr/src/app/dist ./dist

COPY --from=builder /usr/src/app/drizzle ./drizzle
COPY --from=builder /usr/src/app/db ./db

RUN chown -R bun:bun /usr/src/app
USER bun

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD curl -f http://localhost:8080/ || exit 1

CMD ["bun", "run", "dist/server.js"]
