version: '3.8'

services:
  client:
    image: ${REGISTRY:-docker.io}/injurka/trip-scheduler-client:latest
    networks:
      - prod-net
    environment:
      VITE_APP_SERVER_URL: "${VITE_APP_SERVER_URL}"
    deploy:
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.trip-client.rule=Host(`trip-scheduler.limited-dissolve.ru`)"
        - "traefik.http.routers.trip-client.entrypoints=websecure"
        - "traefik.http.routers.trip-client.tls=true"
        - "traefik.http.services.trip-client.loadbalancer.server.port=1420"

  server:
    image: ${REGISTRY:-docker.io}/injurka/trip-scheduler-server:latest
    environment:
      PORT: "8080"
      FRONTEND_URL: "${FRONTEND_URL}"
      VITE_APP_SERVER_URL: "${VITE_APP_SERVER_URL}"
      API_URL: "${API_URL}"
      DATABASE_URL: "${DATABASE_URL}"
      JWT_SECRET: "${JWT_SECRET}"
      DUMP_ENABLED: "${DUMP_ENABLED}"
      BACKEND_URL: "${BACKEND_URL}"
      RESEND_API_KEY: "${RESEND_API_KEY}"
      
      AI_HUBMIX_KEY: "${AI_HUBMIX_KEY}"
      AI_HUBMIX_API_URL: "${AI_HUBMIX_API_URL}"
      
      VAPID_PUBLIC_KEY: "${VAPID_PUBLIC_KEY}"
      VAPID_PRIVATE_KEY: "${VAPID_PRIVATE_KEY}"
      VAPID_SUBJECT: "${VAPID_SUBJECT}"
      
      YANDEX_CLIENT_ID: "${YANDEX_CLIENT_ID}"
      YANDEX_CLIENT_SECRET: "${YANDEX_CLIENT_SECRET}"
      YANDEX_CALLBACK_URL: "${YANDEX_CALLBACK_URL}"
      
      TELEGRAM_API_URL: "${TELEGRAM_API_URL}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_BOT_USERNAME: "${TELEGRAM_BOT_USERNAME}"
      TELEGRAM_MODE: "${TELEGRAM_MODE:-polling}"

      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_REGION: "${S3_REGION}"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      S3_BUCKET: "${S3_BUCKET}"
    networks:
      - prod-net
    deploy:
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.trip-server.rule=Host(`trip-scheduler-api.limited-dissolve.ru`)"
        - "traefik.http.routers.trip-server.entrypoints=websecure"
        - "traefik.http.routers.trip-server.tls=true"
        - "traefik.http.services.trip-server.loadbalancer.server.port=8080"
        - "traefik.http.routers.trip-server.middlewares=trip-server-limit"
        - "traefik.http.middlewares.trip-server-limit.buffering.maxRequestBodyBytes=16777216"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    networks:
      - prod-net
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  prod-net:
    external: true
    name: prod-net

volumes:
  pgdata:
