import type { CountryInfo } from '../models/types'

export const COUNTRIES_DATA: CountryInfo[] = [
  {
    id: 'global',
    name: 'Весь мир',
    flag: '🌍',
    popular: true,
    description: 'Глобальные международные сервисы для путешествий по любым направлениям.',
    tips: [
      {
        title: 'Универсальные приложения',
        text: 'Для международных поездок всегда имейте установленные офлайн-карты (Organic Maps), конвертер валют и сервис для покупки eSIM.',
        icon: 'mdi:lightbulb-outline',
        type: 'tip',
      },
    ],
  },
  {
    id: 'china',
    name: 'Китай',
    flag: '🇨🇳',
    code: 'CN',
    popular: true,
    description: 'Особенности Китая: закрытая цифровая экосистема, безналичная оплата по QR и блокировка сервисов Google.',
    tips: [
      {
        title: 'Великий китайский файрвол (GFW)',
        text: 'Сервисы Google (включая Maps, Gmail, Search), Instagram, WhatsApp, Telegram и Facebook заблокированы. Скачайте проверенный VPN до въезда или используйте роуминговую eSIM (Airalo, Nomad), которая не подвержена цензуре.',
        icon: 'mdi:shield-alert-outline',
        type: 'warning',
      },
      {
        title: 'Навигация и карты',
        text: 'Google Maps в Китае не работает и координаты смещены. Используйте Gaode Maps (Amap) или Apple Maps (на iPhone работают без VPN и показывают китайские карты Gaode).',
        icon: 'mdi:map-marker-alert-outline',
        type: 'warning',
      },
      {
        title: 'Безналичная оплата (Alipay & WeChat)',
        text: 'Наличные и физические карты Visa/Mastercard почти нигде не принимают. Установите Alipay и WeChat Pay заранее и привяжите к ним зарубежную банковскую карту для оплаты по QR-кодам и поездок на метро/такси.',
        icon: 'mdi:qrcode-scan',
        type: 'tip',
      },
      {
        title: 'Бронирование отелей и поездов',
        text: 'Booking.com имеет слабую базу и многие отели не имеют лицензии на иностранцев. Используйте Trip.com (Ctrip) — он гарантирует заселение иностранцев и удобен для покупки билетов на поезда.',
        icon: 'mdi:train-car',
        type: 'tip',
      },
    ],
  },
  {
    id: 'taiwan',
    name: 'Тайвань',
    flag: '🇹🇼',
    code: 'TW',
    popular: true,
    description: 'Удобная транспортная сеть, повсеместная работа Google Maps и развитые сервисы Klook / KKday.',
    tips: [
      {
        title: 'Транспортная карта EasyCard (悠遊卡) / iPASS',
        text: 'Обязательно купите карту EasyCard в аэропорту или магазинах 7-Eleven. Она оплачивает метро MRT в Тайбэе и Гаосюне, городские автобусы, прокат велосипедов YouBike и покупки в магазинах.',
        icon: 'mdi:credit-card-outline',
        type: 'tip',
      },
      {
        title: 'Скидки на скоростной поезд THSR',
        text: 'Для поездок между городами (Тайбэй — Тайчжун — Тайнань — Гаосюн) покупайте билеты на скоростные поезда THSR через Klook или KKday со скидкой 20–30% для иностранных туристов.',
        icon: 'mdi:ticket-percent-outline',
        type: 'tip',
      },
      {
        title: 'Навигация',
        text: 'Google Maps в Тайване работает идеально: точнейшее расписание поездов TRA, THSR, метро и автобусов в реальном времени.',
        icon: 'mdi:google-maps',
        type: 'info',
      },
    ],
  },
  {
    id: 'hong-kong',
    name: 'Гонконг',
    flag: '🇭🇰',
    code: 'HK',
    popular: true,
    description: 'Компактный мегаполис с легендарной картой Octopus и высочайшей плотностью отличных ресторанов.',
    tips: [
      {
        title: 'Карта Octopus (八達通)',
        text: 'Незаменима для метро MTR, автобусов, двухэтажных трамваев Ding Ding, паромов Star Ferry и кафе. На iPhone можно мгновенно выпустить виртуальную карту в приложении Octopus for Tourists прямо в Apple Wallet.',
        icon: 'mdi:cellphone-nfc',
        type: 'tip',
      },
      {
        title: 'Поиск ресторанов и димсамов',
        text: 'Для поиска аутентичной еды и ресторанов используйте местное приложение OpenRice — это главный гастрономический гид Гонконга.',
        icon: 'mdi:silverware-fork-knife',
        type: 'tip',
      },
      {
        title: 'Навигация и интернет',
        text: 'В Гонконге нет файрвола, Google Maps и все западные сервисы работают на максимальной скорости без ограничений.',
        icon: 'mdi:check-circle-outline',
        type: 'info',
      },
    ],
  },
  {
    id: 'japan',
    name: 'Япония',
    flag: '🇯🇵',
    code: 'JP',
    popular: true,
    description: 'Высокотехнологичная сеть поездов, карты Suica/Pasmo в Apple Wallet и культура отзывов на Tabelog.',
    tips: [
      {
        title: 'Карты Suica / Pasmo в Apple Wallet',
        text: 'На iPhone добавьте карту Suica или Pasmo прямо в Wallet за 1 минуту и пополняйте с банковской карты (Mastercard/Amex/JCB). Работает для метро, поездов, комбини и автоматов с напитками.',
        icon: 'mdi:credit-card-chip-outline',
        type: 'tip',
      },
      {
        title: 'Сложные пересадки и синкансэны',
        text: 'Используйте приложение Japan Travel by NAVITIME: оно подсказывает точный вагон для быстрой пересадки, номер платформы и фильтрует маршруты под JR Pass.',
        icon: 'mdi:train',
        type: 'tip',
      },
      {
        title: 'Где искать рестораны (Tabelog)',
        text: 'Японцы строго оценивают заведения: оценка 3.5+ на Tabelog считается превосходной (входит в топ-3% ресторанов страны). Не ориентируйтесь только на 4.8+ в Google Maps.',
        icon: 'mdi:star-outline',
        type: 'tip',
      },
    ],
  },
  {
    id: 'south-korea',
    name: 'Южная Корея',
    flag: '🇰🇷',
    code: 'KR',
    popular: true,
    description: 'Особые картографические правила, супер-аппы Naver/Kakao и удобная карта WOWPASS.',
    tips: [
      {
        title: 'Google Maps ограничен!',
        text: 'Из-за законов о национальной безопасности Google Maps в Южной Корее не умеет строить пешеходные и автомобильные маршруты. Обязательно установите Naver Map или KakaoMap (есть поддержка английского языка).',
        icon: 'mdi:alert-circle-outline',
        type: 'warning',
      },
      {
        title: 'Заказ такси',
        text: 'Приложение Kakao T — безусловный лидер для заказа такси в Сеуле, Пусане и на острове Чеджу.',
        icon: 'mdi:taxi',
        type: 'tip',
      },
      {
        title: 'Карта туриста WOWPASS',
        text: 'Универсальная предоплаченная карта для иностранцев с встроенным чипом T-money для транспорта и возможностью пополнения наличной валютой в терминалах.',
        icon: 'mdi:credit-card-plus-outline',
        type: 'tip',
      },
    ],
  },
  {
    id: 'thailand',
    name: 'Таиланд',
    flag: '🇹🇭',
    code: 'TH',
    popular: true,
    description: 'Популярнейшее направление ЮВА: супер-аппы такси Grab/Bolt, паромы 12Go Asia и скидки на Agoda.',
    tips: [
      {
        title: 'Такси: Grab vs Bolt',
        text: 'Grab — самый надежный сервис с большим автопарком и доставкой еды, но Bolt часто стоит на 20–40% дешевле в Бангкоке и на Пхукете.',
        icon: 'mdi:taxi',
        type: 'tip',
      },
      {
        title: 'Паромы и междугородний транспорт',
        text: 'Для поездок между островами (Самуи, Пханган, Ко Тао, Пхи-Пхи) и поездами бронируйте билеты через 12Go Asia.',
        icon: 'mdi:ferry',
        type: 'tip',
      },
      {
        title: 'Бронирование отелей',
        text: 'В Таиланде и ЮВА сервис Agoda обычно предлагает более низкие цены и больший выбор отелей/вилл, чем европейские агрегаторы.',
        icon: 'mdi:hotel',
        type: 'info',
      },
    ],
  },
  {
    id: 'vietnam',
    name: 'Вьетнам',
    flag: '🇻🇳',
    code: 'VN',
    popular: true,
    description: 'Динамичный Вьетнам: байк-такси Grab/Be, междугородние слипбасы и локальные симки.',
    tips: [
      {
        title: 'Транспорт и байки',
        text: 'Приложения Grab и Be — лучшие способы передвигаться по Ханою, Хошимину и Данангу на мотобайк-такси или авто.',
        icon: 'mdi:motorbike',
        type: 'tip',
      },
      {
        title: 'Междугородние слипбасы и поезда',
        text: 'Сервисы 12Go Asia и Baolau позволяют удобно бронировать спальные автобусы (слипбасы) и поезда между городами.',
        icon: 'mdi:bus',
        type: 'tip',
      },
    ],
  },
  {
    id: 'indonesia',
    name: 'Индонезия (Бали)',
    flag: '🇮🇩',
    code: 'ID',
    popular: true,
    description: 'Островной отдых: супер-апп Gojek, аренда байков и быстрые катера на острова Гили.',
    tips: [
      {
        title: 'Супер-аппы Gojek и Grab',
        text: 'Gojek и Grab — основа жизни на Бали: заказ байк-такси, доставка еды GoFood, вызов авто и доставка покупок.',
        icon: 'mdi:apps',
        type: 'tip',
      },
      {
        title: 'Спидботы на острова',
        text: 'Билеты на скоростные катера из порта Санур на Нуса Пениду, Лембонган и острова Гили удобно бронировать через 12Go Asia или Klook.',
        icon: 'mdi:ferry',
        type: 'tip',
      },
    ],
  },
  {
    id: 'turkey',
    name: 'Турция',
    flag: '🇹🇷',
    code: 'TR',
    popular: true,
    description: 'Стамбул и курорты: карты Яндекс, транспортная Istanbulkart и вызов такси BiTaksi.',
    tips: [
      {
        title: 'Транспорт в Стамбуле (Istanbulkart)',
        text: 'Купите карту Istanbulkart в желтых автоматах на остановках. Она работает для метро, паромов через Босфор, трамвая T1 и фуникулеров.',
        icon: 'mdi:credit-card-outline',
        type: 'tip',
      },
      {
        title: 'Навигация и такси',
        text: 'Яндекс Карты имеют отличную детализацию и расписание транспорта в Турции. Для вызова такси используйте BiTaksi или Uber (вызывает официальное желтое такси по счетчику).',
        icon: 'mdi:map-search-outline',
        type: 'tip',
      },
    ],
  },
  {
    id: 'uae',
    name: 'ОАЭ',
    flag: '🇦🇪',
    code: 'AE',
    popular: true,
    description: 'Дубай и Абу-Даби: карта Nol Card, супер-апп Careem и детализация 2ГИС.',
    tips: [
      {
        title: 'Nol Card в Дубае',
        text: 'Для метро Дубая и трамваев необходима карта Nol Card (серебряная Silver Card — самый выгодный вариант для туристов).',
        icon: 'mdi:train-variant',
        type: 'tip',
      },
      {
        title: 'Навигация и такси',
        text: '2ГИС в Дубае работает отлично и с русскоязычным интерфейсом. Для заказа такси Hala Taxi и доставки еды используйте приложение Careem.',
        icon: 'mdi:taxi',
        type: 'tip',
      },
    ],
  },
  {
    id: 'europe',
    name: 'Европа',
    flag: '🇪🇺',
    popular: true,
    description: 'Шенгенская зона: единые билеты на поезда Omio / Trainline, автобусы FlixBus и Booking.com.',
    tips: [
      {
        title: 'Поезда и автобусы',
        text: 'Для сравнения маршрутов между поездами (Eurostar, DB, SNCF, Renfe, Trenitalia) и автобусами FlixBus используйте Omio или Trainline.',
        icon: 'mdi:train-car',
        type: 'tip',
      },
      {
        title: 'Билеты в музеи без очередей',
        text: 'Для посещения Лувра, Колизея, Саграда Фамилия покупайте билеты с проходом без очереди заранее на GetYourGuide или Tiqets.',
        icon: 'mdi:ticket-outline',
        type: 'tip',
      },
    ],
  },
  {
    id: 'russia',
    name: 'Россия',
    flag: '🇷🇺',
    code: 'RU',
    popular: true,
    description: 'Путешествия по РФ: оплата картами МИР/СБП, Яндекс Карты, РЖД и Островок.',
    tips: [
      {
        title: 'Особенности оплаты',
        text: 'Иностранные карты Visa и Mastercard не работают в РФ. Для оплаты используйте карты МИР, Tinkoff/Сбербанк или переводы по СБП.',
        icon: 'mdi:credit-card-off-outline',
        type: 'warning',
      },
      {
        title: 'Карты и навигация',
        text: 'Яндекс Карты и 2ГИС обеспечивают лучшую детализацию, поэтажные планы зданий и актуальное движение общественного транспорта.',
        icon: 'mdi:map',
        type: 'tip',
      },
      {
        title: 'Бронирование отелей',
        text: 'Booking.com и Airbnb приостановили работу в РФ. Используйте Островок, Яндекс Путешествия или Суточно.ру.',
        icon: 'mdi:hotel',
        type: 'info',
      },
    ],
  },
]
