[package]
name = "trip-scheduler"
version = "0.1.0"
description = "TripScheduler Native Shell"
authors = [ "Ivan Kornilov <injurka@gmail.com>" ]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[lib]
name = "trip_scheduler_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
log = "0.4"
tauri = { version = "2.10.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2.6.0"
tauri-plugin-http = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-opener = "2"
tauri-plugin-geolocation = "2"
reqwest = { version = "0.12", default-features = false, features = [ "rustls-tls" ] }
